### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by jonathanpalma** [peakshift/btc-payer#5]
Add storybook to the current react-native project

https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/

**Comment by johnsBeharry** [comment]
For the storybook setup react-native-web was used by [this project ](https://github.com/Aman035/wallet-ui-react) by @Aman035 which allows storybook.js to be viewable in the web. We shouldn't spend time to try to make incompatible third party components migrated though, only the ones we custom make.

Here's another example of react-native components being shown in the web. https://blixtwallet.github.io
